src/chatle/Controllers/ChatController.cs
using ChatLe.Hubs;
using ChatLe.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR.Infrastructure;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.SignalR;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using ChatLe.ViewModels;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace ChatLe.Controllers
{
    /// <summary>
    /// Chat API controller
    /// </summary>
    [Route("api/chat")]
    public class ChatController : Controller
    {
        private readonly IChatManager<string, ChatLeUser, Conversation, Attendee, Message, NotificationConnection> _chatManager;
        private readonly IHubContext _hub;
        private readonly UserManager<ChatLeUser> _userManager;
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="chatManager">the chat repository manager</param>
        /// <param name="signalRConnectionManager">the SignalR connection manager</param>
        /// <param name="userManager">the Identity user manager</param>
        public ChatController(IChatManager<string, ChatLeUser, Conversation, Attendee, Message, NotificationConnection> chatManager, IConnectionManager signalRConnectionManager, UserManager<ChatLeUser> userManager)
        {
            _chatManager = chatManager;
            _hub = signalRConnectionManager.GetHubContext<ChatHub>();
            _userManager = userManager;
        }
        /// <summary>
        /// Get messages in a conversation
        /// </summary>
        /// <param name="id">the conversation id</param>
        /// <returns>a <see cref="Task<IEnumerable<MessageViewModel>>"/> with the messages list as result</returns>
        // GET: /<controller>/
        [HttpGet("{id}")]
        public async Task<IEnumerable<MessageViewModel>> Get(string id)
        {
            var messages = await _chatManager.GetMessagesAsync(id);
            var users = new List<ChatLeUser>(2);
            var messagesVM = new List<MessageViewModel>(messages.Count());
            foreach (var message in messages)
            {
                var user = users.FirstOrDefault(u => u.Id == message.UserId);
                if (user == null)
                {
                    user = await _userManager.FindByIdAsync(message.UserId);
                    if (user == null)
                        continue;
                }
                messagesVM.Add(new MessageViewModel() { Date = message.Date, From = user.UserName, Text = message.Text });
            }

            return messagesVM;
        }

        /// <summary>
        /// Gets conversations for the current user
        /// </summary>
        /// <returns>a <see cref="Task<IEnumerable<ConversationViewModel>>"/> with the conversations list as result</returns>
        [HttpGet()]
        public async Task<IEnumerable<ConversationViewModel>> Get()
        {
            var userName = HttpContext.User.Identity.Name;
            var conversations = await _chatManager.GetConversationsAsync(userName);
            var length = conversations.Count();
            var users = new List<ChatLeUser>(length);
            var conversationsVM = new List<ConversationViewModel>(length);
            foreach (var conv in conversations)
            {
                var attendees = conv.Attendees;
                var attendeesVM = new List<AttendeeViewModel>(attendees.Count);
                foreach (var attendee in attendees)
                {
                    var u = await _userManager.FindByIdAsync(attendee.UserId);
                    if (u == null)
                        continue;

                    users.Add(u);
                    attendeesVM.Add(new AttendeeViewModel() { UserId = u.UserName });
                }

                if (attendeesVM.Count < 2)
                    continue;

                var messages = conv.Messages;
                var messagesVM = new List<MessageViewModel>(messages.Count());
                foreach (var message in messages)
                {
                    var user = users.FirstOrDefault(u => u.Id == message.UserId);
                    if (user == null)
                    {
                        user = await _userManager.FindByIdAsync(message.UserId);
                        if (user == null)
                            continue;
                    }
                    messagesVM.Add(new MessageViewModel() { Date = message.Date, From = user.UserName, Text = message.Text });
                }

                conversationsVM.Add(new ConversationViewModel() { Id = conv.Id, Attendees = attendeesVM, Messages = messagesVM });
            }

            return conversationsVM;
        }

        /// <summary>
        /// Send a message in a conversation asyncronously
        /// </summary>
        /// <param name="to">the conversation id</param>
        /// <returns>a <see cref="Task"/></returns>
        [HttpPost()]
        public async Task SendMessage(string to, string text)
        {
            var userName = HttpContext.User.Identity.Name;
            var message = new Message() { ConversationId = to, Text  = text, Date = DateTime.Now };
            var conv = await _chatManager.AddMessageAsync(userName, to, message);
            if (conv == null)
                return;
            foreach(var attendee in conv.Attendees)
            {
                var user = await _userManager.FindByIdAsync(attendee.UserId);
                if (user != null && user.UserName != userName)
                    _hub.Clients.Group(user.UserName).messageReceived(new MessageViewModel() { ConversationId = to, Date = message.Date, From = HttpContext.User.Identity.Name, Text = text });
            }            
        }

        /// <summary>
        /// Get or create a one to one conversation asyncronously
        /// </summary>
        /// <param name="to">the second user</param>
        /// <param name="text">the 1st message content</param>
        /// <returns>a <see cref="Task<string>"/> with the conversation id as result or null if the user doesn't exist</returns>
        [HttpPost("conv")]
        public async Task<string> CreateConversation(string to, string text)
        {
            var userName = HttpContext.User.Identity.Name;
            var conversation = await _chatManager.GetOrCreateConversationAsync(userName, to, text);

            var users = new List<ChatLeUser>(conversation.Attendees.Count);
            var attendees = new List<AttendeeViewModel>(conversation.Attendees.Count);
            foreach(var attendee in conversation.Attendees)
            {
                var u = await _userManager.FindByIdAsync(attendee.UserId);
                if (u == null)
                    return null;

                users.Add(u);
                attendees.Add(new AttendeeViewModel() { UserId = u.UserName });
            }
            var messages = new List<MessageViewModel>(conversation.Messages.Count);
            foreach(var message in conversation.Messages)
            {
                var user = users.FirstOrDefault(u => u.Id == message.UserId);
                if (user == null)
                {
                    user = await _userManager.FindByIdAsync(message.UserId);
                    if (user == null)
                        continue;
                }
                messages.Add(new MessageViewModel() { Date = message.Date, From = user.UserName, Text = message.Text });
            }
            _hub.Clients.Group(to).joinConversation(new ConversationViewModel(){ Id = conversation.Id, Attendees = attendees, Messages = messages });
            
            return conversation.Id;
        }

    }
}

src/chatle/Controllers/HomeController.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace ChatLe.Controllers
{
    public class HomeController : Controller
    {
        static ILogger _logger;
        public HomeController(ILoggerFactory factory)
        {
            if (_logger == null)
                _logger = factory.CreateLogger("Unhandled Error");
        }


        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
                return View();

            return RedirectToRoute(new { controller= "Account", action= "Index" });
        }

        public IActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            var feature = this.HttpContext.Features.Get<IExceptionHandlerFeature>();
            var error = feature?.Error;
            _logger.LogError("Oops!", error);
            return View("~/Views/Shared/Error.cshtml", error);
        }
    }
}

src/chatle/Controllers/UserController.cs
using ChatLe.Models;
using ChatLe.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace ChatLe.Controllers
{
    /// <summary>
    /// User api controller
    /// </summary>
    [Route("api/users")]
    public class UserController : Controller
    {
        IChatManager<string, ChatLeUser, Conversation, Attendee, Message, NotificationConnection> _manager;
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="manager">the chat repository manager</param>
        public UserController(IChatManager<string, ChatLeUser, Conversation, Attendee, Message, NotificationConnection> manager)
        {
            _manager = manager;
        }
        /// <summary>
        /// Gets the a connected users list page
        /// </summary>
        /// <returns>a <see cref="Task{UserCollectionViewModel}"/> with the connected user list as result</returns>
        // GET: /<controller>/
        [HttpGet()]
        public async Task<UserCollectionViewModel> Get(int pageIndex = 0)
        {
            var users = await _manager.GetUsersConnectedAsync(pageIndex);
            return new UserCollectionViewModel(users);
        }
    }
}

src/chatle/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/chatle/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/chatle/Views/Home/Index.cshtml
@using System.Security.Principal
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-xs-3">
        <h6>CONNECTED</h6>
        <ul data-bind="foreach: users">
            <li>
                <!-- ko if: $parent.userName !== Id -->
                <a href="#" data-bind="text: Id, click: function() { $parent.showMessage($data); }"></a>
                <!-- /ko -->
                <!-- ko if: $parent.userName === Id -->
                @Html.ActionLink(User.Identity.Name, "Manage", "Account", routeValues: null, htmlAttributes: new { title = "Manage" })
                <!-- /ko -->
            </li>
        </ul>
    </div>
    <div class="col-xs-6">
        <!-- ko with: currentConv -->
        <h6 data-bind="text: title"></h6>
        <form class="form-inline">
            <input id="message" class="form-control" />
            <button type="submit" class="btn btn-default" data-bind="click: function(data, event) { sendMessage('#message'); }">send</button>
        </form>
        <ul data-bind="foreach: messages">
            <li>
                <small data-bind="text: From"></small><br />
                <span data-bind="text: Text"></span>
            </li>
        </ul>
        <!-- /ko -->
        <!-- ko ifnot: currentConv -->
        <h1>WELCOME TO THIS REALLY SIMPLE CHAT</h1>
        <!-- /ko -->
    </div>
    <div class="col-xs-3">
        <h6>CONV</h6>
        <ul data-bind="foreach: conversations">
            <li>
                <a href="#" data-bind="text: title, click: function() { $parent.showConversation($data); }"></a><br />
                <span data-bind="text: messages() && messages()[0] ? messages()[0].Text: null"></span>
            </li>
        </ul>
    </div>
</div>

@section scripts
{
	<environment names="Development">
		<script src="~/lib/knockout/dist/knockout.js"></script>
		<script src="~/lib/signalr/jquery.signalR.js"></script>
		<script src="~/js/chat.js"></script>
	</environment>
	<environment names="Staging,Production">
		<script src="http://ajax.aspnetcdn.com/ajax/knockout/knockout-3.4.0.js"
				asp-fallback-src="~/lib/knockout/dist/knockout.js"
				asp-fallback-test="ko">
		</script>
		<script src="http://ajax.aspnetcdn.com/ajax/signalr/jquery.signalr-2.2.0.min.js"
				asp-fallback.src="~/lib/signalr/jquery.signalR.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.connection">
		</script>
		<script src="~/js/chat.min.js"></script>	
	</environment>
	<script src="/signalr/js"></script>

	<script>
		$(document).ready(function () {
			chatLe.userName = '@User.Identity.Name';
			chatLe.chatAPI = '@Url.Action("Get", "Chat")'
			chatLe.convAPI = '@Url.Action("CreateConversation", "Chat")'
			chatLe.userAPI = '@Url.Action("Get", "User")'

			chatLe.init(true);
		});
	</script>
}